### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by TotteKarlsson** [Arian8j2/ClipboardXX#1]
Does not compile with bcc32..

**Comment by Arian8j2** [comment]
I test that on windows and that working with Bcc32c, Please give me more information about which operating system are you using to compile and what error you get? Thanks for report!

**Comment by Arian8j2** [comment]
Seems that **info about this issue is not complete** and **long time has passed** so, I'm going to close this issue, Create another issue in feature if you want to describe more about your issue, By the way thanks for your report.
