### ISSUE TITLE
Multiple errors when trying to copy

### ISSUE THREAD

**Issue by azrellie** [Arian8j2/ClipboardXX#4]
Whenever I try to copy text to the clipboard using this, it gives errors about it being 'not a class or namespace name' and 'clipboard undeclared identifier' and such and have no idea how to fix this. Am I using it wrong or is it to do with the header file its self?

This is how I'm doing it:
![image](https://user-images.githubusercontent.com/98503938/155857327-b9f5a972-f1ac-4e1c-86ae-b02c68f115fa.png)

Errors:
![image](https://user-images.githubusercontent.com/98503938/155857228-9560ed45-ff5c-4c96-a5b8-dfee9ba65cf3.png)

**Comment by Arian8j2** [comment]
Can you share whole code?

**Comment by azrellie** [comment]
Deleted the "conv" namespace code blocks for more readability.


Code:

#include <Windows.h>
#include "clipboardxx.hpp"
#include "pch.h"
#include "thermodynamics_generator.h"
#include "thermo_functions.h"
#include <string>
#include <iostream>
#include <time.h>
#include <direct.h>	
#include <chrono>
#include <thread>
#include <iomanip>
#include <typeinfo>

using namespace std;
using namespace System;
using namespace Windows::Forms;

/*removed namespaces to make it easier to read*/
// temperature conversions
namespace temp_conv

// speed conversions
namespace speed_conv

// length conversions
namespace length_conv

// formulas
namespace formulas

using namespace temp_conv;
using namespace speed_conv;
using namespace length_conv;
using namespace formulas;

void copy_as_text(string data)
{
	clipboardxx::clipboard clipboard;
	clipboard << data;
}

**Comment by Arian8j2** [comment]
Looks like a simple bug elsewhere, The code for clipboardxx is Ok, Check for some syntax mistakes like missing semicolon etc.

**Comment by azrellie** [comment]
I did lots of double checking for missing semicolons before analyzing the code.
I tried doing the same thing but in a new project and the issue still persists.

Also when I remove these:

**clipboardxx::clipboard clipboard;**
**clipboard << data;**
the errors go away.

**Comment by Arian8j2** [comment]
Did you try it on new empty project? Maybe it's not imported correctly.

**Comment by azrellie** [comment]
Tested it on an empty project and now it seems to be working fine, but doesn't work when used on my forms project. I don't know why its breaking when I use it on my forms project but doesn't break on an empty one.

The code I used in the empty project (just 1 cpp and 1 header file, the header file is the clipboardxx header):

#include "clipboardxx.hpp"
#include < string >

int main()
{
	clipboardxx::clipboard clipboard;
	clipboard << "test string";
	return 0;
}

**Comment by azrellie** [comment]
Still there?

**Comment by Arian8j2** [comment]
Yeap, Sorry for replying late, At this point I'm pretty sure your problem is somewhat going on with whole project that messes up with `clipboardxx` and I'm unable to reproduce that so i really don't how to help but still think sending your whole project may help in some way.

**Comment by azrellie** [comment]
Hm, I see. Well in that case here is the solution then: < link removed >

**Comment by Arian8j2** [comment]
I think you are using the *Visual Studio* form project (I'm not really familiar with that), Did you test it on empty form projects?

**Comment by azrellie** [comment]
I did test it on an empty project, works on that but not forms project for some unexplained reason.

**Comment by Arian8j2** [comment]
I tested it on some `Windows Desktop Application` project and seems to work (But that project was still different to your form app tho, maybe some *Visual Studio* thing that i don't know), I could not get the project that you uploaded too, It needs some premium accounts to download whole folder and downloading it each by each is pure pain, Next time better archive it so that will be easier to upload and download that, At the end I'm still unable to reproduce the error, I'm not familiar to *Visual Studio* stuff, i don't use it, So that's on you i think, If you found the solution please keep me updated.

**Comment by azrellie** [comment]
That sucks. I'll try Google Drive instead.

https://drive.google.com/drive/folders/1Rg3WW92q7HNkTdk8PB3C-baQE9c39fGV?usp=sharing

**Comment by Arian8j2** [comment]
Needs access to see files.

**Comment by azrellie** [comment]
Updated the link, should be accessible now.

**Comment by Arian8j2** [comment]
Move `#include "pch.h"` to first line, See if it get fixed or not.

**Comment by azrellie** [comment]
Now tons of things start breaking (with Windows.h and pch.h above clipboardxx.h).
![image](https://user-images.githubusercontent.com/98503938/156271734-ecd359fb-7ced-4b3d-9ff3-7db6963fa773.png)

With clipboardxx.h on top, the same error still occurs though.
![image](https://user-images.githubusercontent.com/98503938/156271808-691cbd14-f8b3-4d68-85a1-c116772dc80e.png)

**Comment by Arian8j2** [comment]
For some reason it's not linking to windows standard libraries, I don't know why, Maybe you accidentally removed dependencies, To add it again go to **Project** > **Properties** > **Configuration Properties** > **Linker** > **Input** and then paste this for **Additional Dependencies**:
`kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;odbccp32.lib;%(AdditionalDependencies)`

**Comment by azrellie** [comment]
Sadly didn't still does not work (Restarting VS didn't help either).
![image](https://user-images.githubusercontent.com/98503938/156276211-e7a00d6c-6c18-465e-acc8-2097f58503bb.png)

**Comment by Arian8j2** [comment]
> Sadly didn't still does not work (Restarting VS didn't help either). ![image](https://user-images.githubusercontent.com/98503938/156276211-e7a00d6c-6c18-465e-acc8-2097f58503bb.png)

Did you move `#include "pch.h"` to top?
By moving that line and adding dependencies it get fixed for me.

**Comment by azrellie** [comment]
It works now. Apparently I had Windows.h above pch.h because it would always cause errors but now its working. Thanks for the help. 👍

**Comment by Arian8j2** [comment]
Glad to hear it fixed.
