### ISSUE TITLE
Windows data should only be released on failure

### ISSUE THREAD

**Issue by MichaelGoulding** [Arian8j2/ClipboardXX#5]
https://github.com/Arian8j2/ClipboardXX/blob/f35609b0b55618ca53921800afcee966a3aa38fd/include/detail/windows.hpp#L48

See the documentation here: https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setclipboarddata

Also, you might want to do some error checking on the other API calls.   There are some nice LastError to std::exception wrappers available as well.

**Comment by Arian8j2** [comment]
Thanks for submitting issue, I certainly missed this line:
> If SetClipboardData succeeds, the system owns the object identified by the hMem parameter. The application may not write to or free the data once ownership has been transferred to the system

aac9a60 commit will fix this issue.

-------------------
Also thanks for `LastError` advice i added some function to turn `GetLastError` to string so i can append it to exception info.
