### ISSUE TITLE
Cannot copy to clipboard more than once in one program

### ISSUE THREAD

**Issue by milksplash** [Arian8j2/ClipboardXX#6]
Version 0.4
When there are more than 1 copy command in my program, the error below appears at the 2nd copy command:
![error](https://github.com/Arian8j2/ClipboardXX/assets/17235188/239a55c0-3866-4463-ab5c-0ba27cd6548f)
(I am really sorry for the "screenshot", I cannot access the clipboard for screenshotting when the program is debugging)

Here is a simple code that replicates my problem:
```
#include <iostream>
#include "clipboardxx.hpp"

int main()
{
    clipboardxx::clipboard clipboard;
    std::string string;

    std::cin >> string;
    clipboard << string;
    std::cin >> string;
    clipboard << string;
}
```

Please do let me know if you need any more information to follow this up. Thank you in advance.

**Comment by Arian8j2** [comment]
Hello, Update `ClipboardXX` to the latest version, Now it throws better info when cannot open windows clipboard, Write here the full exception message.

**Comment by milksplash** [comment]
Thank you for the reply.

I am unable to replicate the issue in the latest commit (7c9ca9ac06e5b72ae8c6bcc334ad771c6613eaed) nor the 2 commits before it (aac9a60c5f53ef52ebdc84be5e6d23469b13c799 or e055349682bb2b4946a55857b2ff73f84a9bcd4e).

Please let me know if you need me to test anything else. Thank you for the help.

**Comment by Arian8j2** [comment]
Thanks for testing, Some major changes has been done since version `0.4` so it's usual to have bugs in that version, So i think it's time to release version `0.5`, Open another issue if you had any issues with latest release.
